auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317   # ✅ QUAN TRỌNG
        http:
          endpoint: 0.0.0.0:4318   # ✅ Nên thêm nếu dùng HTTP

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h

storage:
  trace:
    backend: s3
    s3:
      endpoint: minio:9000
      insecure: true
      bucket: tempo-trace
      access_key: Tempo
      secret_key: TempoTest
      region: us-east-1

metrics_generator:
  registry:
    external_labels:
      source: tempo