spring:
  application:
    name: fashion-e-commerce-inventory-service
  profiles:
    active: ${PROFILE:dev}
  config:
    import: ${CONFIG_SERVER:configserver:https://config-server.ndlamdev.website/fashion-e-commerce-config-server}
  cloud:
    config:
      username: ${CONFIG_USERNAME:}
      password: ${CONFIG_PASSWORD:}

management:
  endpoints:
    web:
      exposure:
        include: "*"