name: 'fashion-e-commerce-monitoring'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus_api_gateway_localhost.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    restart: unless-stopped
    networks:
      - fashion_e_commerce_monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo
    restart: unless-stopped
    networks:
      - fashion_e_commerce_monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki_container
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - fashion_e_commerce_monitoring

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    container_name: otel_container
    restart: always
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./opentelemetry/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4318:4318" # OTLP http receiver
      - "4317:4317" # OTLP grpc receiver
      - "55679:55679" # zpages extension
    depends_on:
      - tempo
      - loki
    networks:
      - fashion_e_commerce_monitoring

  tempo:
    image: grafana/tempo:latest
    container_name: tempo_container
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200" # tempo
      - "9095:9095" # tempo
      - "4317" # otlp grpc
      - "4318" # otlp grpc
    networks:
      - fashion_e_commerce_monitoring
    depends_on:
      - minio

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_container
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=LamNguyen@1305
    command: server /home/shared --console-address ":9999"
    ports:
      - 9990:9000
      - 9999:9999
    restart: unless-stopped
    volumes:
      - ./data/minio/shared:/home/shared
      - ./data/minio/data:/data
    networks:
      - fashion_e_commerce_monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9990/minio/health/live"]
      interval: 1m30s
      timeout: 30s
      retries: 5

networks:
  fashion_e_commerce_monitoring:
    driver: bridge
