name: "fashion-e-commerce-message-queue"

services:
  # Confluent Kafka broker
  kafka_1:
    image: confluentinc/cp-kafka:7.4.3
    container_name: kafka_broker_1_container
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - fashion_e_commerce_message_queue
    depends_on:
      - zookeeper

  # Confluent Zookeeper instance
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - fashion_e_commerce_message_queue
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper/secrets:/etc/zookeeper/secrets
      - ./data/zookeeper/data:/var/lib/zookeeper/data
      - ./data/zookeeper/log:/var/lib/zookeeper/log

  # Kafka UI for monitoring topics, brokers, etc.
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui_container
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka_1:29092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - fashion_e_commerce_message_queue
    depends_on:
      - kafka_1

networks:
  fashion_e_commerce_message_queue:
    driver: bridge
