spring:
  application:
    name: fashion-e-commerce-profile-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:user_detail_group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "save_user_detail"
            type:
              mapping: "save_user_detail:com.lamnguyen.profile_service.message.SaveUserDetailMessage"
  profiles:
    active: ${PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${application.database}
    url: ${spring.datasource.url}
    locations: classpath:db/migration
  jackson:
    mapper:
      sort-properties-alphabetically: false

server:
  servlet:
    context-path: /api
  port: ${SERVICE_PORT:8004}

application:
  white-list:
    - /greeting

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ZONE:http://localhost:8761/fashion-e-commerce-eureka-server}/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
