receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  logging:
    loglevel: debug
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
    metrics:
      receivers: [ otlp ]
      exporters: [ logging ]
    logs:
      receivers: [ otlp ]
      exporters: [ loki, logging ]