version: "v1.0.0"
name: profile

services:
  server:
    build: .
    restart: on-failure
    container_name: profile_server
    networks:
      - fashion_e_commerce
    ports:
      - "8002:8080"
    image: "fashion-e-commerce:v1.0.0"
    depends_on:
      - server_mysql
      - server_redis
    environment:
      MYSQL_HOST: server_mysql
      MYSQL_USERNAME: fashion_e_commerce
      MYSQL_PASSWORD: dell_doan
      REDIS_HOST: server_redis
      REDIS_PORT: 6379
    volumes:
      - profile_server_volume_data:/data

  server_mysql:
    image: mysql
    container_name: profile_mysql
    networks:
      - fashion_e_commerce
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: fashion_e_commerce
      MYSQL_PASSWORD: ell_doan
      MYSQL_DATABASE: fashion_e_commerce
      MYSQL_ROOT_PASSWORD: 123456@Gio
    volumes:
      - profile_mysql_volume_data:/data

  server_redis:
    image: redis:7.0.15
    container_name: profile_redis
    networks:
      - fashion_e_commerce
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - profile_redis_volume_data:/data

networks:
  fashion_e_commerce:
    driver: bridge

volumes:
  profile_redis_volume_data:
  profile_server_volume_data:
  profile_mysql_volume_data: