spring:
  application:
    name: fashion-e-commerce-cart-service
  profiles:
    active: ${PROFILE:dev}
  config:
    import: ${CONFIG_SERVER:configserver:https://config-server.ndlamdev.website/fashion-e-commerce-config-server}
  cloud:
    config:
      username: ${CONFIG_USERNAME:}
      password: ${CONFIG_PASSWORD:}
      name: fashion-e-commerce-cart-service,eureka-config