spring:
  application:
    name: eureka_service
  config:
    import: ${CONFIG_SERVER:configserver:http://localhost:1305/fashion-e-commerce-config-server}
  cloud:
    config:
      username: ${CONFIG_USERNAME:}
      password: ${CONFIG_PASSWORD:}