server:
  servlet:
    context-path: /fashion-e-commerce-config-server
  port: 1305

spring:
  profiles:
    active: dev
  application:
    name: fashion-e-commerce-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ndlamdev/fashion-e-commerce-config-server
          timeout: 5

management:
  server:
    port: 1306
    base-path: /fashion-e-commerce-config-server
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics